apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidboufkapp
  labels:
    app: oidboufkapp
spec:
  selector:
    matchLabels:
      app: oidboufkapp
  template:
    metadata:
      labels:
        app: oidboufkapp
        version: v1
    spec:
      containers:
        - name: wil42-app
          image: wil42/playground:v1
          ports:
            - containerPort: 8080
      