apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
metadata:
  name: app
  labels:
    app: app
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - application.yaml

commonLabels:
  app: app