apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
metadata:
  name: app
  labels:
    app: app
resources:
  - deployment.yaml
  - service.yaml
  # - application.yaml
  # - ingress.yaml
  - configmap.yaml
  - project.yaml